services:
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:? set in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_PORT: ${DB_PORT:?}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sandboxdb -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  myapp:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      DB: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST:?}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable

volumes:
  db_data: 
