version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sandboxdb
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sandboxdb -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  myapp:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB: postgresql://root:admin@db:5432/sandboxdb?sslmode=disable

volumes:
  db_data: 
